# Generated by Django 4.2.2 on 2023-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
