# Generated by Django 4.2.2 on 2023-07-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
